### ISSUE TITLE
Can't build as non-root because by default it wants to install in /usr/local/bin

### ISSUE THREAD

**Issue by smcameron** [PhilippRados/PShell#1]
Can't build as non-root because it wants to by default install in /usr/local/bin

Attached patch allows:

```
$ make INSTALLDIR=.
src/main.c: In function ‘main’:
src/main.c:858:18: warning: null argument where non-null required (argument 1) [-Wnonnull]
  858 |       int fdin = open(0, O_RDONLY);
      |                  ^~~~
$ ls psh
psh
```

[allow-specifying-install-dir.txt](https://github.com/PhilippRados/PShell/files/8814889/allow-specifying-install-dir.txt)

**Comment by PhilippRados** [comment]
Thanks that is of course a nicer way of handling the permissions.
