### ISSUE TITLE
Why is open() called with NULL path?

### ISSUE THREAD

**Issue by smcameron** [PhilippRados/PShell#2]
```
853       int tmpout = dup(1);
854       int tmperr = dup(2);
855       int fdout;
856       int fderr;
857       pid_t pid;
858       int fdin = open(0, O_RDONLY);
859 
860       for (int i = 0; i < simple_commands_arr.len; i++) {
861         if (!wildcardLogic(simple_commands_arr, &fdout, &fderr, tmpout, tmperr, i)) {
862           continue;
863         }
```

Line 858 calls open with first parameter == 0.  This will always fail with errno set to EINVAL.  Is there a reason for this?

Attached patch removes this superfluous call.

[remove-superfluous-call-to-open.txt](https://github.com/PhilippRados/PShell/files/8815007/remove-superfluous-call-to-open.txt)

**Comment by PhilippRados** [comment]
Thanks for the solution. I saw the warning but thought that you could open stdin like that but that's not the case. I'll change it.
